import '../../public/assets/css/bootstrap-icons.css';
import '../../public/assets/css/bootstrap.min.css';
import '../../public/assets/css/boxicons.min.css';
import '../../public/assets/css/swiper-bundle.css';
import '../../public/assets/css/slick-theme.css';
import '../../public/assets/css/slick.css';
import '../../public/assets/css/style.css';
import 'node_modules/react-modal-video/css/modal-video.css';
import "@/styles/globals.css";
import { useState, useEffect } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { useRouter } from 'next/router';
import Head from 'next/head';
import SmoothPageScroll from '@/components/common/SmoothPageScroll';
import { ThemeContext } from '@/components/ThemeContext';
import OSModal from '@/components/home1/OSModal';

export default function App({ Component, pageProps }) {
  const [theme, setTheme] = useState(() => {
    if (typeof window !== "undefined") {
      const localTheme = localStorage.getItem('theme');
      return localTheme ? localTheme : "light";
    }
    return "light";
  });

  const [modalStep, setModalStep] = useState(0); 
  const router = useRouter();
  const excludedPages = ['/', "/index-2", "/index-3", "/index-4"];

  useEffect(() => {
    const isWindows = () => {
      return /Windows/i.test(navigator.userAgent); 
    };

    if (isWindows()) {
      const modalTimings = [15000, 20000, 10000]; 
      const timeouts = [];

      const showNextModal = (step) => {
        if (step < modalTimings.length) {
          const timeoutId = setTimeout(() => {
            setModalStep(step + 1);
            console.log(`Showing modal ${step + 1}`);
            showNextModal(step + 1);
          }, modalTimings[step]);
          
          timeouts.push(timeoutId);
        }
      };

      showNextModal(0); 

      return () => {
        timeouts.forEach(clearTimeout);
        setModalStep(0); 
      };
    }
  }, []);

  if (theme === "") return null;

  return (
    <>
      <Head>
        <title>JNVKAA - Connect, Inspire, Empower</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/logo/jnvkaa-logo2.png" />
      </Head>
      {modalStep > 0 && <OSModal modalIndex={modalStep - 1} onClose={() => setModalStep(0)} />}

      <ThemeContext.Provider value={{ theme, setTheme }}>
        {excludedPages.includes(router.asPath) ? (
          <>
            <Component {...pageProps} />
            <SmoothPageScroll />
          </>
        ) : (
          <MainLayout>
            <Component {...pageProps} />
            <SmoothPageScroll />
          </MainLayout>
        )}
      </ThemeContext.Provider>
    </>
  );
}
