// VISITED: SUBHRANSHU CHOUDHURY

import '../../public/assets/css/bootstrap-icons.css';
import '../../public/assets/css/bootstrap.min.css';
import '../../public/assets/css/boxicons.min.css';
import '../../public/assets/css/swiper-bundle.css';
import '../../public/assets/css/slick-theme.css';
import '../../public/assets/css/slick.css';
import '../../public/assets/css/style.css';
import 'node_modules/react-modal-video/css/modal-video.css';
import { useEffect } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { useRouter } from 'next/router';
import Head from 'next/head';
import SmoothPageScroll from '@/components/common/SmoothPageScroll';

export default function App({ Component, pageProps }) {
  const router = useRouter();
  const excludedPages = ['/',"/index-2","/index-3","/index-4"]; // Add the paths of excluded pages here

  useEffect(() => {
    import('../../public/assets/js/bootstrap.bundle.min.js');
    import('../../public/assets/js/audio.js');
  }, []);

  if (excludedPages.includes(router.asPath)) {
    // Render the component without the layout for the excluded pages
    return<>
         <Head>
         <title>
        Navodaya - Vidyalaya Samiti, Institute of dreamers
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/images/logo/logo-icon.svg" />
      </Head>
    <Component {...pageProps} />;
    <SmoothPageScroll/>
    </> 
  }

  // Render the component with the layout for other pages
  return (
   <>
    <MainLayout>
      <Component {...pageProps} />
    </MainLayout>
    <SmoothPageScroll/>
   </>
  );
}
