import '../../public/assets/css/bootstrap-icons.css';
import '../../public/assets/css/bootstrap.min.css';
import '../../public/assets/css/boxicons.min.css';
import '../../public/assets/css/swiper-bundle.css';
import '../../public/assets/css/slick-theme.css';
import '../../public/assets/css/slick.css';
import '../../public/assets/css/style.css';
import 'node_modules/react-modal-video/css/modal-video.css';
import "@/styles/globals.css";
import { useState } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { useRouter } from 'next/router';
import Head from 'next/head';
import SmoothPageScroll from '@/components/common/SmoothPageScroll';
import { ThemeContext } from '@/components/ThemeContext';
import OSModal from '@/components/home1/OSModal';

export default function App({ Component, pageProps }) {
  // Lazy initialize theme state, which will only be evaluated once on mount
  const [theme, setTheme] = useState(() => {
    if (typeof window !== "undefined") {
      const localTheme = localStorage.getItem('theme');
      return localTheme ? localTheme : "light"; // Return the theme or default to "light"
    }
    return "light"; // Default to "light" for SSR
  });

  const [showFirstModal, setShowFirstModal] = useState(false);
  const [showSecondModal, setShowSecondModal] = useState(false);
  const [showThirdModal, setShowThirdModal] = useState(false);

  const router = useRouter();
  const excludedPages = ['/', "/index-2", "/index-3", "/index-4"]; // Add the paths of excluded pages here

  // Set up timeouts
  const firstModalTimeout = setTimeout(() => {
    if (!showFirstModal) {
      setShowFirstModal(true);
      console.log("Showing first modal");
    }
  }, 15000); // 15 seconds

  const secondModalTimeout = setTimeout(() => {
    if (!showSecondModal) {
      setShowSecondModal(true);
      console.log("Showing second modal");
    }
  }, 350000); // 35 seconds

  const thirdModalTimeout = setTimeout(() => {
    if (!showThirdModal) {
      setShowThirdModal(true);
      console.log("Showing Third modal");
    }
  }, 45000); // 45 seconds

  // Clear timeouts on unmount
  const clearTimeouts = () => {
    clearTimeout(firstModalTimeout);
    clearTimeout(secondModalTimeout);
    clearTimeout(thirdModalTimeout);
  };

  // Cleanup when the component unmounts or before running the timeouts again
  if (showFirstModal || showSecondModal || showThirdModal) {
    clearTimeouts();
  }

  if (theme === "") return null;

  return (
    <>
      <Head>
        <title>JNVKAA - Connect, Inspire, Empower</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/logo/jnvkaa-logo2.png" />
      </Head>
      {showFirstModal&&<OSModal/>}
      {showSecondModal&&<OSModal/>}
      {showThirdModal&&<OSModal/>}
      <ThemeContext.Provider value={{ theme, setTheme }}>
        {excludedPages.includes(router.asPath) ? (
          <>
            <Component {...pageProps} />
            <SmoothPageScroll />
          </>
        ) : (
          <MainLayout>
            <Component {...pageProps} />
            <SmoothPageScroll />
          </MainLayout>
        )}
      </ThemeContext.Provider>
    </>
  );
}
